### ISSUE TITLE
Making a speical page for different language implementations of JSON5

### ISSUE THREAD

**Issue by DonaldTsang** [json5/json5-spec#14]
For example
- PHP https://github.com/colinodell/json5 and https://github.com/kujirahand/JSON5-PHP
- Go https://github.com/yosuke-furukawa/json5 and https://github.com/json5/json5-go and https://github.com/flynn/json5
- Rust https://github.com/callum-oakley/json5-rs
- Python https://github.com/Kijewski/pyjson5 and https://github.com/dpranke/pyjson5
- C# https://github.com/json5/json5-dotnet

(including other repos outside of json5)

**Comment by jordanbtucker** [comment]
Thanks for this list. We already have a place for this on the [JSON5 Wiki](https://github.com/json5/json5/wiki/In-The-Wild). Can you please add these there?

**Comment by DonaldTsang** [comment]
@jordanbtucker could you open a page for it? It currently redirect to main
