### ISSUE TITLE
Documentation: Comparison and design decision of other "languages"

### ISSUE THREAD

**Issue by DonaldTsang** [json5/json5-spec#21]
It might be a good idea to compare JSON5 with the features of these languages (and of course YAML, TOML, CSON, INI and others that are popular)
- https://github.com/dhall-lang/dhall-lang
- https://github.com/hashicorp/hcl
- https://github.com/archipaorg/icl
- https://github.com/mrkkrp/liaison
- https://github.com/ron-rs/ron
- https://github.com/svenvc/ston
- https://github.com/Sygmei/Vili

**Comment by jordanbtucker** [comment]
I think this belongs in the Wiki.
