### ISSUE TITLE
Feature: constant names (unquoted string literals)

### ISSUE THREAD

**Issue by mindplay-dk** [json5/json5-spec#26]
I just thought of a way to further reduce the noise in configuration files and the like.

What if we allowed unquoted string literals?

For example:

    { foo: bar }

That's not a JS feature, but it is JS compatible syntax - it merely presumes `bar` is a `const`, which has been predefined with the value `"bar"`.

Thoughts?

**Comment by jordanbtucker** [comment]
Thanks for the suggestion, but any features that are incompatible with ES5 will not be implemented.
