### ISSUE TITLE
Dictionaries may have a single trailing comma.

### ISSUE THREAD

**Issue by ThePix** [json5/json5-spec#27]
The readme says arrays may have a single trailing comma; what about dictionaries?

The argument for this is the same as it is for arrays (though I guess it is more common to use arrays).

This may already be the case, in which case the readme coiuld usefully be updated.

**Comment by jordanbtucker** [comment]
Thanks for submitting this issue, but are you sure you have the right repo? The readme for this repo just points to the spec, which does say that objects can have trailing commas. And the readme for the [json5 library](https://github.com/json5/json5) also mentions this.
