### ISSUE TITLE
Replace mandatory braces with indentation

### ISSUE THREAD

**Issue by ioggstream** [json5/json5-spec#41]
Dear folks, removing mandatory quoting and comments are great!

```
{
  // comments
  unquoted: 'and you can quote me on that',
  singleQuotes: 'I can use "double quotes" here',
  trailingComma: 'in objects', andIn: ['arrays',],
}
```

What do you think about replacing mandatory braces with indentation?
This will make "nested objects for humans"!
Brackets can be replaced with some sort of prefix, like `-`

e.g.

```
// comments
unquoted: 'and you can quote me on that'
singleQuotes: 'I can use "double quotes" here'
trailingComma: 'in objects',
andIn: 
- 'arrays'

```
WDYT?

**Comment by jordanbtucker** [comment]
This looks a lot like [YAML](https://yaml.org/).

**Comment by nocturn9x** [comment]
The second proposal definitely does, but IMHO there is no reason for JSON not to allow trailing commas
