### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [json5/json5-spec#47]
My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245. For instance, specific to this repository, I'd like to be able to ask whether JSON5 allows standard `{"Quoted Key Name": ""}` like JSON(C) does.

**Comment by jordanbtucker** [comment]
Done!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/json5/json5-spec/issues/47#event-11494005251

Thanks, @jordanbtucker. I've asked the question at https://github.com/json5/json5-spec/discussions/48#discussion-6082604.
