### ISSUE TITLE
feature-request: Multi 'chunk' string literals like: "abc" "def"

### ISSUE THREAD

**Issue by msokalski** [json5/json5-spec#9]
One thing I like in C/C++ is ability to code string literals in multiple lines while keeping indentation.
Currently with JSON5 best we can do is to use back-slashes which kill indentation:
```
{
    text: "Dobra dobra \
zupa z bobra."
}
```
What I'd love to see in JSON5 is:

```
{
    text: "Dobra dobra "
          "zupa z bobra."
}
```
Limiting it to be not allowed on object's keys would be fine for me.

**Comment by msokalski** [comment]
- Maybe to make it (more) compatible with ECMAScript, we should force using '+' operator between chunks?
- Would that make more sense if we also allow coding numerical values using using arithmetic operators?
- One may ask why not supporting math functions, I'd say just because they are functions, just to end such discussion as soon as possible :P.

**Comment by jordanbtucker** [comment]
See also https://github.com/json5/json5/issues/106 and https://github.com/json5/json5/pull/111
